### ISSUE TITLE
krocket

### ISSUE THREAD

**Issue by dianjuar** [kevteg/zsh-themes#1]
# Requirement
### PLEASEEEEEEEE

Please limit in your theme **`krocket`** the path to just the last three directories like the other themes :'(
![screenshot_2016-08-20_19-43-12](https://cloud.githubusercontent.com/assets/7026066/17834454/dbcb6108-670e-11e6-9f53-d223edeccbfb.png)

**Comment by kevteg** [comment]
Hey Diego!, I don't understand what you mean by that :(

**Comment by kevteg** [comment]
Ohhh I understand now!. Will see what I can do

**Comment by kevteg** [comment]
Solved!
